# Site settings
title: "Camouflage"
bye_message: "f4184fc596403b9d638783cf57adfe4c75c605f6356fbc91338530e9831e9e16"
baseurl: "/Bitcoin-Camouflage/"
url: "https://blockchaincommons.github.io"
disqus: bitcoincamouflage

# Header settings
nick: "bitcoincamouflage"
mail:
    domain: "pm"
    ext: "me"
fingerprint_key: "3452 BFEE EC3B 116D B2AE BE4D 97A2 95D7 0E86"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
